README.md
Advised to install this before server side packages as they will not downgrade for client side packages once they're installed too.
=> Specified apolloclient dependency @^0.5.0

src/smart-apollo.js
Either the documentation is outdated or the current release. As I found the naming `watchLoading` way more intuitive than `loadingChangeCb` I assume it should be renamed.
=> Renamed option loadingChangeCb to watchLoading

src/smart-apollo.js
fixes #65 
when the data hasn't changed, `nextResult` is not called and `loading` stays true. 
this resets loading in the promise returned from `refetch`.
=> fix refetch + watchLoading when no new results are returned

.babelrc, .gitignore, package.json, rollup.config.js
Initial pass at rollup to knock out a build script to compile and minify.  Will run this in project tomorrow.
Size difference
Previous Compile: 6 files & 31 kB
Current Build: 1 file & 20kB
resolves #61 
One thing to discuss is thoughts on source maps.  I set it to not include them to reduce the size of the library.  What do you think?
=> Add build script using rollup

README.md
Added a short description to the readme telling people that the `prefetch` and `variables` options need to match or the query result will not be populated while rendering server-side.
=> Added info on prefetch/variables mismatch

.gitignore, .npmignore, package.json, types/index.d.ts, types/test/App.ts, types/test/index.ts, types/test/tsconfig.json, types/vue-apollo.d.ts, types/vue.d.ts, yarn.lock
Many Vue projects have TypeScript declarations inside itself and support TypeScript.
[vue-router](https://github.com/vuejs/vue-router), [vuex](https://github.com/vuejs/vuex), etc...
I want to support TypeScript on our project too.
I implement typescript declarations and run typed test for [this example](https://github.com/Akryum/vue-apollo-example).
(added `yarn run test:types` command)
I thought I checked all the APIs, but please let me know if there are missing parts.
=> TypeScript support

src/smart-apollo.js
When running query, sometimes I want to set the results to a different data value than the name of the query. This works fine when using `manual` mode, however, an error is thrown that tell me that the key doesn't exist in the results.
In manual cases, I don't think an error should be thrown.
=> Don't require the key to match the query name

types/vue-apollo.d.ts
Hello,
I am working on a project with Vue and Typescript. When I try to define multiple endpoints with below code:
```
const apolloProvider = new VueApollo({
clients: {
dev: endpoint1,
t2: endpoint2,
},
defaultClient: endpoint1,
})
```
There has TypeScript error that is described at below:
```
TS2345: Argument of type '{ clients: { dev: ApolloClient<NormalizedCacheObject>; t2: ApolloClient<NormalizedCacheObject>; }...' is not assignable to parameter of type '{ de
faultClient: ApolloClient<{}>; defaultOptions?: VueApolloOptions | undefined; }'.
Object literal may only specify known properties, and 'clients' does not exist in type '{ defaultClient: ApolloClient<{}>; defaultOptions?: VueApolloOptions | undefined; }'.
```
=> fix TypeScript error when multiple clients are used

README.md
Link to `watchQuery` API in docs is broken, see: #268
=> Fixed watchQuery link

src/smart-query.js
This short circuits unproductive cache work for no-cache queries that will not exist
=> no-cache smart queries are throwing exceptions in optimistic UI updates

src/components/ApolloQuery.js
Right now `loading` is only set when a result is received, not when the request is sent. Using `watchLoading`, we can pass the loading state from when the request is sent.
=> Pass back `isLoading` to scoped-slot

src/smart-query.js
Trying to solve #212 and probably some other issues where `loading of undefined` appears on Nuxtjs with child routes
@Akryum I'm not sure if this will solve the issue but I face exactly the issue where  a getter on loading is called even though the queries is empty. I have this issue on call of historyBack() from child route back to parent page.
=> relax getter on loading

types/apollo-provider.d.ts, types/index.d.ts, types/options.d.ts, types/test/App.ts, types/test/index.ts, types/test/willPrefetch.ts, types/vue-apollo.d.ts, types/vue.d.ts, yarn.lock
Update type definition according to the below commit.
https://github.com/Akryum/vue-apollo/commit/66504309599ce9d4a31feb8fd5f065d790349c86
- remove `apolloProvider` propery from `ComponentOptions` extended.
- now use `provide` props provided by public.(ref: https://vuejs.org/v2/api/#provide-inject)
- add `prefetch` props to apollo query option.
- add below APIs to ApolloProvider(VueApollo default exported).
- provide: (key?: string) => this
- prefetchAll: (context: any, components: VueApolloComponent[], options?: { includeGlobal?: boolean }) => Promise<ApolloQueryResult<any>[]>
- getStates(options?: { exportNamespace?: string }): { [key: string]: any }
- exportStates(oprions?: { globalName?: string, attachTo?: string, exportNamespace?: string}): string
=> Update typed apollo provider

types/vue-apollo.d.ts
Currently, there are no Typescript definitions for `addSmartQuery`. This PR adds one line to cover that edge case.
=> Add Typescript type for addSmartQuery()

docs/guide/apollo/mutations.md
Before: https://www.apollographql.com/docs/react/reference/index.html#ApolloClient.mutate
After: https://www.apollographql.com/docs/react/essentials/mutations.html#render-prop
=> docs: fix broken apollo doc link for `mutate`

docs/guide/installation.md, docs/guide/local-state.md
Adds instructions for apollo boost:
https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost
Also adds example of local state that is more verbose: https://codesandbox.io/s/x2jr96r8pp
=> Add Apollo boost

docs/guide/README.md
This PR fixes a minor typo on the docs changing `developped` to `developed`
=> Fix typo on docs. Change developped to developed

src/dollar-apollo.js
I found that smart queries are started on server-side even when their `prefetch` is false. This causes useless network requests and API calls.
I think this is not an intended behavior.
=> SmartQuery shouldn't be auto-started on server when prefetch is false

docs/api/apollo-mutation.md, src/components/ApolloMutation.js
=> Add clientId in ApolloMutation component

types/options.d.ts
Hi,
I'm currently migrating my Vue components from _basic_ syntax to _decorated_ syntax by using [vue-class-component](https://github.com/vuejs/vue-class-component) and [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator), and I faced a problem.
```vue
<template>
<div>...</div>
</template>
<script lang="ts">
import gql from 'graphql-tag';
import { Component, Vue } from 'vue-property-decorator';
@Component({
apollo: {
language: {
query: gql`{ ... }`,
variables() {
return {
language: this.language,
};
},
error() {
this.error = true;
},
watchLoading(isLoading) {
this.loading = isLoading;
},
},
},
})
export default class HelloWorld extends Vue {
language = 'fr';
error = false;
loading = false;
}
</script>
```
When compiling this code, I have the following error …
=> feat(typescript): specify "this" type for "watchLoading"

src/components/ApolloMutation.js, src/components/ApolloQuery.js
Would be useful if the user could pass `undefined` as the `tag` prop in order to create a renderless component and skip the tag creation. Some times this extra level of elements could mess things up with the page layout (e.g. flexbox, etc)
Letting the user decide whether the component render the slot inside a tag (div by default) or without any extra render would be a plus.
Thanks
=> Let the ApolloQuery be a renderless component if `tag` prop is undefined

docs/api/dollar-apollo.md, types/test/App.ts, types/vue-apollo.d.ts, types/vue.d.ts
This change reimplements the TypeScript bindings for `$apollo`, adding a lot of missing functionality. 
I've tried to only expose fields that are in the documented API. For that I added `$apollo.query` to the documentation as it is the method that I'm currently in need of, which spurred me to submit this PR.
Most of the methods in `SmartQuery` seemed to internally map to their equivalent method in `apollo-client`'s `ObservableQuery`, so I made their type declarations proxy to their respective methods on `ObservableQuery`. I have intentionally not done that with `$apollo.query`, `$apollo.mutate` and `$apollo.subscribe` because not only does `vue-apollo` allow them to accept a more comprehensive set of `options`, there is currently a [major issue with the type declaration of …
=> Add missing TypeScript declarations to $apollo

src/components/ApolloMutation.js, src/components/ApolloQuery.js
this.$scopedSlots.default({}) returns an array of length one for the vNode, and the render function is expecting the vNode by itself. This fixes this bug in the current renderless functionality.
=> Fix error in renderless rendering

types/vue.d.ts
Fixes apollo option in TypeScript definitions by renaming it to apolloProvider
=> Fix apollo option in TypeScript definitions

ssr/index.js, ssr/utils.js
Some fixes for the new SSR implementation:
- The component resolver should allow camelCase and PascalCase names in options.components
- `no-prefetch` doesn't work
- `prefetch: true` is not documented but should be allowed for backward compatibility
- On making fake instances:
- `localData(vm)` → `localData.call(vm)`
- Inject computed properties, methods, `$data`, `$props`, etc.
- Use Object.assign instead of spread properties (which may causes a syntax error in some environments)
=> Fix new SSR API

src/smart-query.js
Since v3.0.0-beta.14, query subscription is restarted after an error. This works well in most cases, but if an error occurs and subsequent queries hit the cache, the same error is thrown repeatedly instead of the correct value being fetched from the cache.
To demonstrate the behavior, let's say we have a resolver which accepts two arguments - value, and do_throw. if do_throw is false the resolver simply echoes value and if do_throw is true it throws an error with value.
Pseudocode:
```
executeApollo({"value":"1","do_throw":false}) // 1
executeApollo({"value":"12","do_throw":false}) // 12
executeApollo({"value":"123","do_throw":true}) // GraphQL error: Error: 123
executeApollo({"value":"1","do_throw":false}) // GraphQL error: Error: 123 (incorrect) …
```
=> Fixes repeatedly throwing incorrect errors when queries hits cache immediately after an Apollo error

docs/guide/apollo/README.md
Add a stentence regarding Apollos own defaultOptions.  
Some other users inclduing myself found this a bit confusing and I hope to help others. Not sure if this is wanted/needed or maybe I got something wrong.
=> chore(docs): clarify defaultOptions settings

docs/api/dollar-apollo.md, types/apollo-provider.d.ts, types/options.d.ts, types/test/App.ts, types/test/index.ts, types/vue-apollo.d.ts
update type definitions
fix: https://github.com/Akryum/vue-apollo/issues/409
- add clients and defaultClient property to ApolloProvider
- enable to use `this.$apollo.provider.defaultClient` by this
- remove client property from DollerApollo
- enable to specify client name to query
- enable to specify client name when request query
```
// use `test` client to request
this.$apollo.query({ query: gql`query mockQuery { id }`, client: 'test' })
```
=> Catch up typings of dollar apollo

src/smart-query.js
Related to #462 #456
Currently when you execute the same query more than once, every subscriptions made on this query will be removed. 
- attach subscribeToMore to a query
- execute the query _(the subscription is now correctly bind to the query)_
- execute the same query a second time _(the subscription is now removed from the query and the smart subscription will be ignored as the variables did not changed)_
This use case may be found when you use vue-apollo inside a vue-supply container.
I made an example of this scenario [here](https://github.com/karlito40/vue-apollo-testing). You will have to change the vue-apollo package to 3.0.0-beta.26 if you need to see the bug in action.
My workaround is to ignore the query call when no changes has been made since the last call.
=> Fix subscribeToMore being removed from the observer

src/smart-query.js, src/smart-subscription.js
Add the query key as an additional to the result callback function, to allow the callback function to identify which query the result is coming from.  This is very useful to use allow manual SmartQuery instances to take action based on what type or client of query is incoming.  This is particularly crucial when trying to use vue-apollo to connect to multiple backends with the same schema (#216).
=> Add query key as additional parameter to result callback, #445

src/mixin.js
This fixes an annoying issue when running specifications in mocha where apolloProvider may not be configure in the specification.
=> Issue 532: Check for provided truthiness.

docs/guide/installation.md
Cookies are not sent to server if following current Installation docs. `HttpLink` is no longer used, use `createHttpLink` instead ([Apollo Link docs](https://www.apollographql.com/docs/react/recipes/authentication#cookie)).
=> docs: updated doc according to Apollo Link doc

docs/api/smart-subscription.md
Correction to code example. The real method is "refresh", not "restart".
=> Typo in smart-subscription.md

src/smart-subscription.js
Hi, 
This fix allows to use `result` and `updateQuery` at same time.
My change will be more revealing than any explanation.
=> fix: updateQuery with result hook

src/mixin.js
When `skip` in query option is true or can be computed as true, the `start` method in `SmartApollo` won't be triggered, and it leads to `serverPrefetch` can't get a valid resolve function and block server side rendering.
=> fix: ssr blocking when `skip` is true

src/smart-query.js
Had a problem with skipped queries being stuck with `loading = true` forever.
I think that `stop()` should invoke `loadingDone()` so that stopped query isn't reporting itself as loading.
=> Invoke loadingDone when stopping SmartQuery

types/options.d.ts
`(context: any) => any | boolean` was technically `(context: any) => (any | boolean)` which ultimately resolves to `(context: any) => any`.
`skip` and `prefetch` can take a plain boolean, so this fixes that issue.
=> Fix `skip` and `prefetch` query options definitions

types/options.d.ts
prefetch type should be `((context: any) => any) | boolean` instead of `(context: any) => (any | boolean)`, which cause a ts typecheck error when we pass in a boolean variable.
=> Fix prefetch type

docs/guide/apollo/subscriptions.md
Maybe it's just me, but I was struggeling with this.
Expecting such result:
```
data: { 
messageChanged: {
type: "added",
message: {…},
__typename: "MessageChanged"
}
}
```
According to the current docs I expected to be able to just write
```
console.log(data.messageChanged)
```
but then I get `undefined`.   
Instead I need to destruct data like `({data})` to be able to do this.  
I kinda find this consufing. I might be expectional stupid though.   
Maybe there's a better way to describe this or improve the docs.  
Happy to help out here and update this with whatever might make this clearer.
=> docs: clarify data usage for subscriptions

types/vue.d.ts
We can access the Apollo provider like `this.$apolloProvider.defaultClient.resetStore()`
=> fix(ts): Add missing declarations to $apolloProvider

docs/guide/apollo/subscriptions.md
Property 'operation' does not exist on type 'OperationDefinitionNode | FragmentDefinitionNode'
I changed it like it is written in the apollo docs: https://www.apollographql.com/docs/react/advanced/subscriptions
And it works.
=> I got a TypeScript Error with the written way:

docs/guide/local-state.md
On the local schema declared mutations are "changeItem" and "addItem", but the next steps refers to "checkItem".
=> Fix example mutation name

package.json, ssr/index.js, tests/demo/package.json, tests/unit/ssr.test.js, yarn.lock
This PR closes #158 
- Serialized javascript in SSR export by default
- Adds serialize-javascript library for handling that
- Adds jest to test the unit
We have been using serialize-javascript for this in production for a long time now (at least a year) on a pretty large usage of apollo and has been rock solid.
=> Serialize SSR against XSS

types/options.d.ts
```sh
ERROR in /Users/harmandeeppannu/Desktop/app/tailwind-ts-app/node_modules/vue-apollo/types/options.d.ts
47:18 Interface 'VueApolloMutationOptions<V, R>' incorrectly extends interface 'MutationOptions<R, OperationVariables>'.
Types of property 'optimisticResponse' are incompatible.
Type 'Object | ((this: ApolloVueThisType<V>) => any) | undefined' is not assignable to type 'R | ((vars: OperationVariables) => R) | undefined'.
Type 'Object' is not assignable to type 'R | ((vars: OperationVariables) => R) | undefined'.
The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
Type 'Object' is not assignable to type 'R'.
The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
45 | }
46 |
> 47 | export …
```
=> Typescript compilation error with latest apollo package

docs/api/apollo-subscribe-to-more.md
The description was difficult to understand, simplified in an attempt to improve clarity.
=> docs: clarify updateQuery prop on SubscribeToMore

docs/api/dollar-apollo.md, types/vue-apollo.d.ts
I could not find any existing discussion on whether this field should be included or not. But the code base indicates it exists :)
=> The typings for DollarApollo where missing `getClient`

build/rollup.config.base.js
This PR externalizes the peer dependencies in vue-apollo in order to reduce the bundle size of vue-apollo in the default umd build.  Without this, all of those libraries are being included and compiled in a way that is not tree-shakable, which causes the bundle size to be quite large.  
Closes #660 
|Library|Before|After WithExternals|
|---|---|---|
|esm|133k|57k|
|min|52k|26k|
|umd|142k|61k|
```bash
drwxrwxr-x  2 talos talos   4096 Jul  5 11:50 .
drwxrwxr-x 16 talos talos   4096 Aug  7 10:26 ..
-rw-rw-r--  1 talos talos 133190 Aug  7 10:27 vue-apollo.esm.js
-rw-rw-r--  1 talos talos  52935 Aug  7 10:26 vue-apollo.min.js
-rw-rw-r--  1 talos talos 142186 Aug  7 10:27 vue-apollo.umd.js
drwxrwxr-x  2 talos talos  4096 Jul  5 11:50 .
drwxrwxr-x 16 talos talos  4096 Aug  7 10:26 ..
-rw-rw-r-- …
```
=> (build) Externalize apollo and graphql libraries

types/options.d.ts
The `VariableFn<V>` type incorrectly returns any `Object` type, rather than the type specified by `V`. This is a small change but has a high impact on type correctness.
This resulted in an easily preventable typing bug in our app. Here is a simplified example:
```
apollo: {
project (): VueApolloQueryOptions<ProjectQueryVariables, ProjectQuery> {
return {
variables: { projectId: 5 }, // ❌ should be just id, but the type isn't checked 😢
query: PROJECT_QUERY,
fetchPolicy: 'network-only'
}
}
}
```
This means that the `variables` key of a few important things don't actually check `V` `variables` type:
- `ApolloVueSubscribeToMoreOptions<V>`
- `VueApolloQueryOptions<V, R>`
- `VueApolloMutationOptions<V, R>`
- `VueApolloSubscriptionOptions<V, R>`
=> Fix VariableFn<V> type returns Object instead of V

docs/api/apollo-provider.md, src/apollo-provider.js, src/mixin.js
This PR adds the ability to turn off prefetching globally during SSR.
Background and usage:
We have a very large graph that serves out requests.  Sometimes we will get in a situation where we need to be able to troubleshoot a slow or bad server side render.  During this we will normally add a query parameter and if that is preset, we bypass graphql.  
With the move to 3.0 and nuxt we no longer have the option to getMatchedComponents and manually run the vue-apollo queries, so to get that behavior we need a way to signal to vue-apollo to not make the requests.
=> (feat) add global prefetch apollo provider option

docs/guide/installation.md
Add instruction about integration Vue Apollo with Webstorm. Due to this change syntax highlighting in Webstorm will work correctly
=> Add Webstorm integration instruction

src/smart-apollo.js
Reactive pollInterval.
Example:
````
apollo: {
allMessages: {
query:gql`query { allMessages { done id information} }`,
pollInterval() {
return this.shouldPoll ? 300 : null
},
}
}
````
=> Enhancement #453 Reactive pollInterval.

types/options.d.ts
=> Revert "Fix VariableFn<V> type returns Object instead of V"

babel.config.js, package.json
Continuing from #807, compile `for...of` to plain for loops to improve support in IE 11.
=> Compile for...of to plain for loops

packages/docs/src/guide/apollo/subscriptions.md
When server supports that.
So current documentation is slightly opinionated about one approach of doing reactivity with GraphQL. I think we should explain that other things are possible.
=> Explain that simple subscriptions can be used for live queries

packages/docs/src/api/apollo-mutation.md, packages/docs/src/api/apollo-query.md, packages/docs/src/api/smart-query.md, packages/docs/src/guide/apollo/mutations.md, packages/docs/src/guide/apollo/queries.md, packages/docs/src/migration/README.md, packages/docs/src/zh-cn/api/apollo-mutation.md, packages/docs/src/zh-cn/api/apollo-query.md, packages/docs/src/zh-cn/api/smart-query.md, packages/docs/src/zh-cn/guide/apollo/queries.md, packages/docs/src/zh-cn/migration/README.md
Somewhere along the line, the official Apollo docs have updated their docs such that most of the links in vue-apollo's docs break. Hence, all links have been updated so that they redirect somewhere.
Note that unfortunately direct targets for some items (notably props/options) don't exist, so where necessary, a "best alternative" was chosen.
=> Fix all broken links throughout docs

package.json
The glob in the `package.json` `build` is incompatible with Darwin bash/zsh glob format, and probably others. This patch just wraps the glob in quotes so it is passed as a literal to `lerna`, instead of being incorrectly expanded.
=> v4: Fix build glob portability

packages/vue-apollo-composable/src/useResult.ts
`useResult` is great for reactive objects, but the unwrapped type is currently inferred as `any`. This results in unnecessary and unsafe casting. The type information is available to be inferred, but the `useResult` function is not using it.
This PR fixes the issue by providing stricter type inference to `useResult` and `computed` for the `defaultValue` and `pick` return values, which results in correct typing.
**Issue**
```graphql
interface ProjectQuery {
project: Project
}
```
Usage:
```typescript
const { result, loading } = useQuery<ProjectQuery>(...)
const project = useResult(result, {}, data => data.project)
```
❌ Typed as `const project: Readonly<Ref<Readonly<any>>>`
**PR Fix**
Usage:
```typescript
const { result, loading } = useQuery<ProjectQuery>(...)
const project = …
```
=> v4: Fix useResult type inferring 'any'

packages/vue-apollo-composable/src/useApolloClient.ts, packages/vue-apollo-composable/src/useMutation.ts
=> just remove blank

packages/docs/src/guide/testing.md
It's a small addition to testing doc showing how we can mock loading state when testing components with Apollo queries
=> docs: added instructions about mocking loading state

packages/docs/src/guide-composable/mutation.md
This MR adds a small example with overriding mutation options. Might be specifically useful for the mutations where we need to pass a parameter available only in the template (for example, in `v-for` loop or any kind of scoped slot) to `update` hook.
=> docs (v4): added example of overriding mutation options

packages/vue-apollo-composable/src/useMutation.ts
Currently, `useMutation` is defined to not allow `document` or `options` to be a `Ref`. It works as expected, it just needs to be unwrapped in `mutate`. Here is example code that breaks in v4-alpha4, but works after this PR.
```typescript
const randomName = ref('')
const options = ref({ variables: { id: 1, name: randomName } })
// ❌ v4-alpha4 causes a type error on `options`
// ✅ works correctly after the PR
const { mutate } = useMutation(RandomNameMutation, options)
// button @click="randomizeName"
function randomizeName () {
randomName.value = Math.random().toString()
mutate()
}
```
In this case, clicking the `button` correctly runs the mutation with a new random name value every time.
---
*This PR resolves one of several issues found while creating a …
=> v4: Fixes useMutation not taking a Ref

packages/vue-apollo-composable/src/useMutation.ts
This fixes a type error in `useMutation`'s exported `mutate` function that required arguments to be specified, even though the intention was that [they are optional](https://v4.apollo.vuejs.org/guide-composable/mutation.html#variables). 
(This appears to have been caused by a typo - the first argument of `mutate` had a default value, but the second one didn't. I'm surprised that TypeScript didn't catch this.)
```typescript
const { mutate } = useMutation(...)
// ❌ v4-alpha4: Expected 2 arguments, but got 0
// ✅ works after this PR
mutate()
```
---
*This PR resolves one of several issues found while creating a [graphql-code-generator](graphql-code-generator.com/) plugin for vue-apollo hooks, which can be tracked [here](https://github.com/dotansimha/graphql-code-generator/pull/3146).*
=> v4: Fix useMutation "mutate" optional arguments

packages/vue-apollo-composable/package.json, packages/vue-apollo-composable/src/useApolloClient.ts, packages/vue-apollo-composable/src/useMutation.ts, packages/vue-apollo-composable/src/useQuery.ts, packages/vue-apollo-composable/src/useResult.ts, packages/vue-apollo-composable/src/useSubscription.ts, packages/vue-apollo-composable/src/util/ExtractSingleKey.ts, packages/vue-apollo-composable/tests/fixtures/graphql-example-types.ts, packages/vue-apollo-composable/tests/types/assertions.ts, packages/vue-apollo-composable/tests/types/tsconfig.json, packages/vue-apollo-composable/tests/types/useApolloClient-types.test.ts, packages/vue-apollo-composable/tests/types/useLoading-types.test.ts, packages/vue-apollo-composable/tests/types/useMutation-types.test.ts, packages/vue-apollo-composable/tests/types/useQuery-types.test.ts, packages/vue-apollo-composable/tests/types/useResult-types.test.ts, packages/vue-apollo-composable/tests/types/useSubscription-types.test.ts, packages/vue-apollo-composable/tests/types/util/ExtractSingleKey.test.ts
There are currently a lot of TypeScript edge cases in v4 alpha where calling function with certain signatures would not strictly type the expected arguments, or would result in `any` being part of the return types. This was caused by missing overloads for the hooks that determined types by how they were called.
**This PR intentionally does not change *any* behavior, it only adds type coverage and tests.**
- **adds the missingTypeScript function overloads for all hooks**, so that calling with the different arguments results in correct types both for inputs and outputs
- **adds (almost) complete coverage for types**, excepting excepting the cases where `strict` is required, or where a failure is expected, [which TypeScript does not currently …
=> v4 alpha: Add full test coverage for TypeScript hook types & fix missing overloads

packages/vue-apollo-composable/src/useMutation.ts, packages/vue-apollo-composable/tests/types/useMutation-types.test.ts
I came across issue #910 during development, where you can't call `useMutation` fully typed without giving it initial variables.
This pull request makes the variables argument in `mutate` required, when you provide `useMutate` with `TVariables`, but no options or variables property in the options.
=> Add typings for late variables in useMutation

packages/vue-apollo/package.json, yarn.lock
Resolves #993 vulnerability https://nvd.nist.gov/vuln/detail/CVE-2020-7660
=> Fixes #993 - Upgrade serialize-javascript to 4.0.0

packages/vue-apollo/src/smart-query.js
`ObservableQuery.currentResult` has been renamed to
`ObservableQuery.getCurrentResult` and the former has been removed in
Apollo Client 3. To maintain compatibility with Apollo Client 2, it
checks whether `getCurrentResult` exists before calling.
refs #917
=> fix: apollo 3 compatibility

packages/vue-apollo/src/index.js
https://github.com/vuejs/vue-apollo/issues/924
Added the recommended sanity check .hasOwnProperty that is best practice for .defineProperty to fix .$apollo redefinition bug when using more than one Vue application on a page, or multiple vue built standard web components, like a web component library.
This bug is a show stopper for using vue-apollo in standard web components but fortunately was easily fixable by adding the standard best practices check around the block to prevent redefinition.
Also worth noting that it appears this same issue it has occurred and crept back into this project several times.
=> Fix for Issue #924 (Cannot Re-assign $apollo)

packages/vue-apollo/src/smart-query.js
Currently a query with `pollInterval` set will start polling on the server during SSR, which leads to the polling happening indefinitely. This PR simply trims the `pollInterval` option to Apollo when running on the server.
=> fix(ssr): ignore pollInterval on server

packages/vue-apollo/src/smart-query.js
Currently on error the promises used in `serverPrefetch` are being rejected with no value. Vue doesn't consider this to be an error, which leads to a broken response where the component is not rendered, but SSR considered the render successful, so it's not possible to detect the error.
This should fix #897 and #900.
@Akryum, a quick merge would be appreciated, as currently it's a bit worrisome to use in production since a transient network error could lead to clients getting a broken response.
=> fix(ssr): reject serverPrefetch with error

packages/vue-apollo-composable/src/useMutation.ts, packages/vue-apollo-composable/src/useQuery.ts, packages/vue-apollo-composable/src/useSubscription.ts, packages/vue-apollo-composable/tests/types/useMutation-types.test.ts, packages/vue-apollo-composable/tests/types/useQuery-types.test.ts, packages/vue-apollo-composable/tests/types/useSubscription-types.test.ts
This fixes #961, fixes #948, fixes #998, and closes #955. Also should fix the issue raised in https://github.com/dotansimha/graphql-code-generator/issues/3679.
The problem was that I added typing in #895 with the expectation that if `TVariables` was specified, then `variables` should be required. This is not the case, since queries, subscriptions, and mutations can have variables that are all optional. This is written up in #961.
This has the positive benefit of simplifying the Frankenstein's Monster that the types in `useMutation` were becoming.
=> fix(ts): allow undefined for optional variables

packages/vue-apollo-composable/src/useMutation.ts
Thank you for a very useful library.
I couldn't overwrite the variable specified by the initial value in mutate, so I fixed it.
When I wrote the following code, I couldn't overwrite a variable.
I think it would be better to make it overwritable, how about that?
```typescript
const DELETE_PRODUCT = gql`
mutation DeleteProduct($id: Int!) {
delete_products(where: {id: {
_eq: $id
}}){
returning {
id
name
}
}
}
`
const { mutate: deleteProduct } = useMutation<
DeleteProductMutation,
DeleteProductMutationVariables
>(DELETE_PRODUCT, () => ({
variables: {
id: 0
},
refetchQueries: [{ query: FETCH_PRODUCTS }]
}));
const onDeleteProduct = (productId: number) => {
deleteProduct({ id: productId }); 
// At the time of request, the id of the variable will be the '0' specified at the time of useMutation …
```
=> (v4) Be able to overwrite variables in mutate

packages/test-e2e-composition/package.json, packages/test-ssr-composition/package.json, packages/vue-apollo-composable/package.json, packages/vue-apollo-composable/src/useQuery.ts, packages/vue-apollo-composable/src/useSubscription.ts, packages/vue-apollo-composable/src/util/loadingTracking.ts, packages/vue-apollo-composable/src/util/paramToReactive.ts, packages/vue-apollo-composable/src/util/paramToRef.ts, yarn.lock
this fixes #1001
With the change of @vue/composition-api v0.6.0, the behavior of the watch API changed. 
https://github.com/vuejs/composition-api/ releases/tag/v0.6.0
> The lazy option of watch has been replaced by the The opposite immediate option, which defaults to false. (It's ignored when using the effect signature). 
This will prevent useQuery from executing the query immediately.
This PR includes the following changes
- Update @vue/composition-api (to v0.6.1)
- Add immediate option to the use of the watch API
- Fix type errors
=> (V4) Update @vue/composition-api to v0.6.1

packages/vue-apollo-composable/src/useQuery.ts
Fixes #940
After evaluating a few alternatives, this one performed reliably on all my components.
- If onServerPrefetch the query is not enabled or prefetch is disabled, resolve firstResult
- If start is cancelled and a firstResult is pending, resolve firstResult
- If stop is called and firstResult is pending, resolve firstResult
The remaining cases are coverd with the old conditions.
- If query returns an error and firstResult is pending, reject with firstReject
- If query completes successfully and firstResult is pending, resolve firstResult
=> fix: unresolved promises in ssr (#940)

packages/docs/src/.vuepress/config.js
To make it clear that it's 1 among 3 ways of using vue-apollo. 
Before, I thought there were 2 ways:
After:
=> Rename Components -> Component API in header

packages/docs/src/guide/README.md, packages/docs/src/guide/apollo/queries.md, packages/docs/src/guide/ssr.md, packages/docs/src/guide/testing.md, packages/docs/src/zh-cn/guide/README.md, packages/docs/src/zh-cn/guide/apollo/queries.md, packages/docs/src/zh-cn/guide/testing.md
These changes enclose every mention of `vue-apollo` in backticks, to make it consistent across all the docs.
=> docs: enclose vue-apollo in backticks

packages/vue-apollo-composable/src/util/loadingTracking.ts
@Akryum  In Vue 2's composition API, the instance has a [`vm.$root` property](https://github.com/vuejs/composition-api/blob/master/src/component/componentProxy.ts#L15) with the root component.
However, in Vue 3, the [property is called `vm.root`](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/component.ts#L179) (without dollar).
With this small change I was able to upgrade a project using latest `@vue/apollo-composable` alpha to Vue 3.
=> Fix getAppTracking for Vue 3 support

packages/docs/src/api/smart-query.md
Show both static value usage and reactive prop usage.
=> docs(smart-query): document `pollInterval` usage

packages/vue-apollo-composable/src/useQuery.ts
`onServerPrefetch` only exists in Vue 2's composition API, not in Vue 3 as far as I know.
=> Fix useQuery to support Vue 3

packages/vue-apollo-composable/src/useMutation.ts, packages/vue-apollo-composable/src/useQuery.ts, packages/vue-apollo-composable/src/useSubscription.ts, packages/vue-apollo-composable/src/util/useEventHook.ts
`useEventHook` param is currently marked optional.
This disables the possibility to destructure the query/mutation results directly in the callback parameter.
For example:
```typescript
const { onResult } = useQuery(document);
onResult(({ data: { queryField } }) => {
// use queryField
});
```
would currently yield a typescript error:
```
Property 'data' does not exist on type 'ApolloQueryResult<any> | undefined'
```
(note the `| undefined` also the event is declared as `const resultEvent = useEventHook<ApolloQueryResult<any>>()`)
This PR solves the issue.
It is safe because:
- it only affects the type system, not the actual JS code
- nowhere in the source tree `trigger` is called with an undefined value (at least not in a way allowed by the type system)
- a possibly undefined result can …
=> v4: mark useEventHook param as not optional

packages/docs/src/.vuepress/config.js, packages/docs/src/fr/README.md, packages/docs/src/fr/api/README.md, packages/docs/src/fr/api/apollo-mutation.md, packages/docs/src/fr/api/apollo-provider.md, packages/docs/src/fr/api/apollo-query.md, packages/docs/src/fr/api/apollo-subscribe-to-more.md, packages/docs/src/fr/api/dollar-apollo.md, packages/docs/src/fr/api/smart-query.md, packages/docs/src/fr/api/smart-subscription.md, packages/docs/src/fr/api/ssr.md, packages/docs/src/fr/guide/README.md, packages/docs/src/fr/guide/apollo/README.md, packages/docs/src/fr/guide/apollo/mutations.md, packages/docs/src/fr/guide/apollo/pagination.md, packages/docs/src/fr/guide/apollo/queries.md, packages/docs/src/fr/guide/apollo/special-options.md, packages/docs/src/fr/guide/apollo/subscriptions.md, packages/docs/src/fr/guide/components/README.md, packages/docs/src/fr/guide/components/mutation.md, packages/docs/src/fr/guide/components/query.md, packages/docs/src/fr/guide/components/subscribe-to-more.md, packages/docs/src/fr/guide/installation.md, packages/docs/src/fr/guide/local-state.md, packages/docs/src/fr/guide/multiple-clients.md, packages/docs/src/fr/guide/ssr.md, packages/docs/src/fr/guide/testing.md, packages/docs/src/fr/migration/README.md
This PR translates the Vue Apollo documentation in French.
Since there were no guidelines on how to PR translations, I made a single big PR, taking the example of the pending Spanish translation PR.
I did my best to follow the [vuejs-fr terminology](https://github.com/vuejs-fr/vuejs.org/issues/4).
fix #919
=> feat: Vue Apollo docs in French 🇫🇷

packages/vue-apollo/src/smart-query.js
Close #492 
Currently, when the component is fetching data from the cache, the `nextResult` method is called explicitly by `executeApollo` when `loading` is not `false`. This doesn't involve Apollo Observable subscription and leads to calling query `result` hook twice: once by `executeApollo` and once by `observer.next`
This PR attempts to fix this behaviour
=> Fixed calling result hook twice when fetching data from cache

packages/vue-apollo-composable/src/useQuery.ts
When receiving new results (either because `pollInterval`is set or because `.refetch()` was called), any errors that were previously caught are kept in cache. This means that subsequent updates will always continue to see the last error, even if the latest response from the server was OK. This PR adresses that by explicitly clearing any existing errors before handling new results.
This should address #1119.
=> fix(composable): Clear previous error when recieving a result
