- src/smart-apollo.js
> fix: clone options to avoid sharing state between multiple instances

- README.md
`loading` instead of `loader` as parameter
> Typo in result hook in README

- README.md
> Typo in Query Component Doc

- types/options.d.ts
> Updating Diff/Omit type definitions for TypeScript 2.9

- src/components/ApolloQuery.js
> Move times outside of the result data structure

- docs/api/apollo-provider.md
> Make watchLoading documentation clearly

- docs/guide/apollo/pagination.md
See issue: https://github.com/Akryum/vue-apollo/issues/375
> Add a warning from my pain

- docs/guide/apollo/mutations.md
This variable name confused me at first in the documentation, so I provide a fix for the documentation in this PR.
> Fix an error in the mutations documentation

- docs/api/smart-query.md
- docs/guide/apollo/mutations.md
- docs/guide/apollo/pagination.md
- docs/guide/apollo/queries.md
- docs/guide/apollo/subscriptions.md
- docs/guide/local-state.md
- docs/guide/testing.md
Make codes in docs also fit for standard style
> docs: unify style in docs

- docs/api/apollo-query.md
- docs/api/smart-subscription.md
- docs/guide/ssr.md
- docs/migration/README.md
- docs/zh-cn/README.md
- docs/zh-cn/api/apollo-mutation.md
- docs/zh-cn/api/apollo-query.md
- docs/zh-cn/api/dollar-apollo.md
- docs/zh-cn/api/smart-query.md
- docs/zh-cn/api/smart-subscription.md
- docs/zh-cn/api/ssr.md
- docs/zh-cn/guide/README.md
- docs/zh-cn/guide/local-state.md
- docs/zh-cn/guide/ssr.md
- docs/zh-cn/migration/README.md
Just a suggestion: maybe a stable version of vue-apollo can be published after this wonderful ssr refactor?
> docs: sync Chinese doc to 3.0.0-beta.28

- docs/guide/apollo/subscriptions.md
It wasn't very clear that it i needed to attach the subscription to a smart query.
> Clarifying it must be a smart query

- docs/guide/multiple-clients.md
It took me a bit of digging and research to figure out how to get this to work. I hope that the example expanded below would help others implement this more easily.
> Add more complete example of multiple client configuration

- docs/guide/local-state.md
Reworked local state management doc to match Apollo 2.5 state management
> docs: Local state management

- docs/api/smart-subscription.md
Not sure if this is correct, but it seems to work.
> Add error to smart subscription docs

- docs/api/apollo-mutation.md
- docs/api/apollo-query.md
- docs/guide/components/mutation.md
- docs/guide/components/query.md
- docs/zh-cn/api/apollo-mutation.md
- docs/zh-cn/api/apollo-query.md
- docs/zh-cn/guide/components/mutation.md
- src/components/ApolloQuery.js
- src/smart-apollo.js
`occured` => `occurred`
In docs & error messages.
> Minor spelling correction

- docs/guide/apollo/README.md
- docs/guide/apollo/queries.md
avoid this newbie gotcha https://github.com/Akryum/vue-apollo/issues/700
> Clarify a common newbie gotcha

- docs/api/ssr.md
Adds docs related to option here
https://github.com/Akryum/vue-apollo/blob/b67878e52a60efb57f567d253fb61d0bcc7f5c6b/ssr/index.js#L6
> Update SSR Docs for serializer options.

- docs/zh-cn/guide/multiple-clients.md
Fixed the wrong variable name `clientBptions`
> Fixed the wrong variable name

- ssr/index.d.ts
I run my entryServer through webpack using TypeScript, so have found a need for these.
> Add TypeScript typings for ssr

- types/vue.d.ts
> fix(types): $apolloProvider should not be optional

- packages/vue-apollo/src/smart-query.js
@Akryum please merge it as it brakes GraphQL while using it in SSR mode.
> fix: check errors.length on array

- packages/docs/src/guide-composable/query.md
Added a note that it refetches the query when modified.
> (docs) Updated variable refs section

- docs/api/smart-query.md
Hey @Akryum 
fixing a broken link.
Cheers!
> docs: fixing broken link

- packages/vue-apollo-composable/src/useSubscription.ts
Remove direct reference to Vue
> Update useSubscription to support Vue 3
